# [START swagger]
swagger: "2.0"
info:
  description: "API for Quran"
  title: "Quran API"
  version: "1.0.0"
host: "utopian-button-227405.appspot.com"
# [END swagger]
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - "https"
paths:
  "/v1/audio":
    get:
      description: "Echo back a given message."
      operationId: "echo"
      produces:
        - "application/json"
      responses:
        200:
          description: "Echo"
          schema:
            $ref: "#/definitions/echoMessage"
definitions:
  echoMessage:
    type: "object"
    properties:
      message:
        type: "string"
# Does not require an API key.
security: []
